### ISSUE TITLE
Problem to connect to F5 from plugin

### ISSUE THREAD

**Issue by ndestor** [f5devcentral/f5-eclipse-plugin#1]
The connection to BIGIP management address doesn't work, the error printed is:
"Cannot connect 10.x.x.x : Not reachable
Analysed on Wireshark, the TCP connexion try to be established on destination port 7, why? My F5 doesn't listen on that port.  

Tested on Win10, ECLIPSE Oxygen.1a Release (4.7.1a)

**Comment by rreichenbach** [comment]
Port 7 (TCP echo) is used by the Eclipse plugin to see if the provided IP is "reachable" before sending a Rest request.  Here is the method being called to do that: https://docs.oracle.com/javase/1.5.0/docs/api/java/net/InetAddress.html#isReachable(int)

It's called with a timeout of 5000 (5 seconds).

So, check to make sure the host on which Eclipse is being run can connect to your big-ip.  Can you ping it?  Perhaps port 7 is being blocked somewhere between the two systems?  Perhaps your connectivity is slow and thus the 5 second timeout is exceeded before it decides it is reachable.

**Comment by ndestor** [comment]
Sorry it's my issue. I just see that F5 minimum version required for this plugin is 12.1, currently using version 11.5.4 HF1...

My F5 reject TCP echo port 7 if port lockdown is set to "Allow Default" (ICMP is working well). 
Added port 7 in custom list and getting a new issue after, a compatibility error i think:
10.x.x.x Cannot connect : 
java.lang.NullPointerException

**Comment by rreichenbach** [comment]
Yes, TMOS 12.1 is a minimum for the plugin.  That will give you support for iRules and iRulesLX.  For iAppLX and iControlLX support, TMOS 13.1 is required.  Closing this issue unless you still have problems with any of those TMOS versions.
