### ISSUE TITLE
Invalid version error when connecting to a Beta image deployment

### ISSUE THREAD

**Issue by cipmarg** [f5devcentral/f5-eclipse-plugin#5]
It looks like because the release numbering on the Beta images is non-standard, Eclipse trows this error when adding the device:

![image](https://user-images.githubusercontent.com/40606792/41964459-55a5278e-79fa-11e8-8fcc-0cd5d7c79c89.png)

The image file is: BIGIP-bigip13.1.x-roxy-13.1.0.5.0.0.0.1-0.0.23.iso
![image](https://user-images.githubusercontent.com/40606792/41964796-436e7312-79fb-11e8-90bf-5e96efbc9744.png)

**Comment by adam-f5** [comment]
Repository Archived
