### ISSUE TITLE
Failed to connect to BIGIP

### ISSUE THREAD

**Issue by zhanglingsir** [f5devcentral/f5-eclipse-plugin#6]
Failed to connect to BIGIP-13.1.3.4
192.168.174.128 cannot connect: Sent Rest Request

![image](https://user-images.githubusercontent.com/49258053/105680089-3d800f80-5f2a-11eb-84ce-f6b335712504.png)
But I can open it from the browser

**Comment by seldomcouth** [comment]
> Failed to connect to BIGIP-13.1.3.4 192.168.174.128 cannot connect: Sent Rest Request
> 
> ![image](https://user-images.githubusercontent.com/49258053/105680089-3d800f80-5f2a-11eb-84ce-f6b335712504.png) But I can open it from the browser

Did you ever resolve this? I am experiencing the same issue. I can connect via the iControl path in a browser but I see the same error you do from Eclipse.

**Comment by zhanglingsir** [comment]
可能是ssh的按钮没有打开，在plantform里面有ssh的按钮开关.


It may be that the ssh button is not turned on, and there is a ssh button switch in plantform..


发自我的iPhone

------------------ Original ------------------
From: GitCouth ***@***.***&gt;
Date: 周二,5月 24,2022 03:47
To: f5devcentral/f5-eclipse-plugin ***@***.***&gt;
Cc: zhanglingsir ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [f5devcentral/f5-eclipse-plugin] Failed to connect to BIGIP (#6)





  
Failed to connect to BIGIP-13.1.3.4 192.168.174.128 cannot connect: Sent Rest Request
 
 But I can open it from the browser
  
Did you ever resolve this? I am experiencing the same issue. I can connect via the iControl path in a browser but I see the same error you do from Eclipse.

**Comment by seldomcouth** [comment]
> It may be that the ssh button is not turned on, and there is a ssh button switch in plantform..

_SSH Access_ is enabled in F5 System > Platform settings. Is there something on the Eclipse side that needs to be enabled?

**Comment by adam-f5** [comment]
Repository Archived
